# Not compatible w/ Jekyll
MD002: false # first-heading-h1/first-header-h1: First heading shoudl be a top level heading
MD041: false # first-line-h1: First line in file should be a top level heading

# Disagree:
MD026: false # no-trailing-punctuation: Trailing punctuation in heading
MD033: false # no-inline-html

# Not sure about:
MD045: false # no-alt-text: images should have alternate text

# FIXME:
MD036: false # no-emphasis-as-heading: Emphasis used instead of a heading
MD013: false # line length
